# Generated by Django 5.0.6 on 2024-06-15 04:11

import django_ckeditor_5.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Note',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='Untitled', max_length=200, verbose_name='Title')),
                ('text', django_ckeditor_5.fields.CKEditor5Field(default='Your default content here.', verbose_name='Content')),
            ],
        ),
    ]
