# Generated by Django 5.0.6 on 2024-06-15 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0003_article_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
    ]
