# Generated by Django 5.0.6 on 2024-06-16 09:27

import django_ckeditor_5.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0005_remove_article_image_remove_article_text_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='content',
        ),
        migrations.AddField(
            model_name='article',
            name='text',
            field=django_ckeditor_5.fields.CKEditor5Field(default=None, verbose_name='Text'),
        ),
    ]
