# Generated by Django 5.0.6 on 2024-06-16 09:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0008_alter_article_text'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='text',
        ),
    ]
