# Generated by Django 5.0.2 on 2024-03-18 16:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='timetableentry',
            table='timetable',
        ),
    ]
